// Scenario categories for organizing topics
export const SCENARIOS = [
  { id: 'everyday', label: 'Everyday Life', icon: '☀️', description: 'Daily conversations and common situations' },
  { id: 'professional', label: 'Professional', icon: '💼', description: 'Workplace, interviews, and career' },
  { id: 'academic', label: 'Academic', icon: '📚', description: 'Education, learning, and knowledge' },
  { id: 'social', label: 'Social & Culture', icon: '🤝', description: 'Relationships, traditions, and society' },
  { id: 'opinion', label: 'Opinion & Debate', icon: '💬', description: 'Express views on current issues' },
  { id: 'creative', label: 'Creative & Fun', icon: '🎨', description: 'Imagination, storytelling, and hobbies' },
];

export const TOPICS = [
  // ─── Everyday Life ───
  { id: 1, category: 'everyday', title: 'Self Introduction', difficulty: 'Beginner',
    subtopics: ['Personal Background', 'Family', 'Strengths', 'Hometown'],
    keywords: ['name', 'age', 'hometown', 'skills', 'goals', 'personality'] },
  { id: 2, category: 'everyday', title: 'Daily Routine', difficulty: 'Beginner',
    subtopics: ['Morning Habits', 'Work/Study', 'Evening Relaxation', 'Weekend Plans'],
    keywords: ['wake up', 'schedule', 'tasks', 'habits', 'commute', 'productive'] },
  { id: 3, category: 'everyday', title: 'Food & Dining', difficulty: 'Beginner',
    subtopics: ['Favorite Food', 'Cooking at Home', 'Restaurant Experience', 'Street Food'],
    keywords: ['dishes', 'taste', 'ingredients', 'cuisine', 'recipe', 'order'] },
  { id: 4, category: 'everyday', title: 'Shopping', difficulty: 'Beginner',
    subtopics: ['Online Shopping', 'Bargaining', 'Preferences', 'Return & Exchange'],
    keywords: ['price', 'discount', 'buy', 'market', 'brand', 'payment'] },
  { id: 5, category: 'everyday', title: 'Health & Fitness', difficulty: 'Intermediate',
    subtopics: ['Exercise Routine', 'Diet & Nutrition', 'Mental Health', 'Doctor Visits'],
    keywords: ['workout', 'nutrition', 'stress', 'healthy', 'yoga', 'sleep'] },
  { id: 6, category: 'everyday', title: 'Travel & Tourism', difficulty: 'Intermediate',
    subtopics: ['Favorite Destination', 'Trip Planning', 'Budget Travel', 'Cultural Experiences'],
    keywords: ['journey', 'destination', 'explore', 'hotel', 'flight', 'adventure'] },
  { id: 7, category: 'everyday', title: 'Weather & Seasons', difficulty: 'Beginner',
    subtopics: ['Favorite Season', 'Weather Impact', 'Seasonal Activities', 'Climate Differences'],
    keywords: ['sunny', 'rain', 'winter', 'summer', 'monsoon', 'temperature'] },
  { id: 8, category: 'everyday', title: 'Home & Living', difficulty: 'Beginner',
    subtopics: ['Dream Home', 'Neighborhood', 'Interior Design', 'City vs Village'],
    keywords: ['apartment', 'room', 'furniture', 'garden', 'neighbors', 'comfort'] },
  { id: 9, category: 'everyday', title: 'Transportation', difficulty: 'Beginner',
    subtopics: ['Commuting', 'Public Transport', 'Driving', 'Future of Transport'],
    keywords: ['bus', 'metro', 'traffic', 'cycle', 'uber', 'electric'] },

  // ─── Professional ───
  { id: 10, category: 'professional', title: 'Job Interview', difficulty: 'Advanced',
    subtopics: ['Self Pitch', 'Common Questions', 'Salary Negotiation', 'Follow-up'],
    keywords: ['resume', 'HR', 'skills', 'strengths', 'weakness', 'experience'] },
  { id: 11, category: 'professional', title: 'Career Goals', difficulty: 'Intermediate',
    subtopics: ['Dream Job', 'Skills Needed', 'Future Plans', '5-Year Vision'],
    keywords: ['ambition', 'success', 'growth', 'profession', 'promotion', 'passion'] },
  { id: 12, category: 'professional', title: 'Workplace Communication', difficulty: 'Intermediate',
    subtopics: ['Email Etiquette', 'Meetings', 'Giving Feedback', 'Conflict Resolution'],
    keywords: ['colleague', 'manager', 'deadline', 'project', 'collaborate', 'report'] },
  { id: 13, category: 'professional', title: 'Leadership & Teamwork', difficulty: 'Advanced',
    subtopics: ['Leader Qualities', 'Team Dynamics', 'Decision Making', 'Delegation'],
    keywords: ['leader', 'responsibility', 'motivate', 'trust', 'vision', 'inspire'] },
  { id: 14, category: 'professional', title: 'Public Speaking', difficulty: 'Advanced',
    subtopics: ['Overcoming Stage Fear', 'Structuring a Speech', 'Engaging the Audience', 'Body Language'],
    keywords: ['speech', 'audience', 'communication', 'confidence', 'presentation', 'persuade'] },
  { id: 15, category: 'professional', title: 'Entrepreneurship', difficulty: 'Advanced',
    subtopics: ['Business Ideas', 'Startup Culture', 'Funding', 'Risk vs Reward'],
    keywords: ['startup', 'investor', 'market', 'product', 'profit', 'innovation'] },
  { id: 16, category: 'professional', title: 'Client Meetings', difficulty: 'Advanced',
    subtopics: ['Introductions', 'Presenting Ideas', 'Handling Objections', 'Closing Deals'],
    keywords: ['proposal', 'negotiate', 'contract', 'relationship', 'value', 'pitch'] },

  // ─── Academic ───
  { id: 17, category: 'academic', title: 'Education System', difficulty: 'Intermediate',
    subtopics: ['School Life', 'Exams & Grading', 'Online Learning', 'Education Reform'],
    keywords: ['studies', 'exams', 'learning', 'degree', 'university', 'research'] },
  { id: 18, category: 'academic', title: 'Technology & AI', difficulty: 'Advanced',
    subtopics: ['Gadgets', 'Artificial Intelligence', 'Internet & Privacy', 'Future Tech'],
    keywords: ['smartphone', 'apps', 'innovation', 'digital', 'automation', 'robot'] },
  { id: 19, category: 'academic', title: 'Environment & Climate', difficulty: 'Advanced',
    subtopics: ['Pollution', 'Climate Change', 'Conservation', 'Sustainable Living'],
    keywords: ['nature', 'recycle', 'global warming', 'carbon', 'renewable', 'ecosystem'] },
  { id: 20, category: 'academic', title: 'Science & Innovation', difficulty: 'Advanced',
    subtopics: ['Space Exploration', 'Medical Breakthroughs', 'Inventions', 'Scientific Method'],
    keywords: ['experiment', 'discovery', 'research', 'theory', 'progress', 'technology'] },
  { id: 21, category: 'academic', title: 'Books & Reading', difficulty: 'Beginner',
    subtopics: ['Favorite Book', 'Reading Habits', 'Genres', 'Benefits of Reading'],
    keywords: ['novel', 'author', 'story', 'knowledge', 'fiction', 'library'] },
  { id: 22, category: 'academic', title: 'Problem Solving', difficulty: 'Advanced',
    subtopics: ['Critical Thinking', 'Real-Life Situations', 'Creative Solutions', 'Logical Approach'],
    keywords: ['logic', 'decision', 'approach', 'analyze', 'strategy', 'resolve'] },
  { id: 23, category: 'academic', title: 'History & Heritage', difficulty: 'Intermediate',
    subtopics: ['Historical Events', 'Famous Personalities', 'Monuments', 'Lessons from History'],
    keywords: ['ancient', 'civilization', 'revolution', 'culture', 'museum', 'legacy'] },

  // ─── Social & Culture ───
  { id: 24, category: 'social', title: 'Friendship', difficulty: 'Beginner',
    subtopics: ['Best Friend', 'Qualities of a Good Friend', 'Childhood Memories', 'Long-distance Friendships'],
    keywords: ['trust', 'support', 'bond', 'fun', 'loyalty', 'memories'] },
  { id: 25, category: 'social', title: 'Family & Relationships', difficulty: 'Beginner',
    subtopics: ['Family Values', 'Parenting', 'Sibling Bond', 'Joint vs Nuclear Family'],
    keywords: ['parents', 'siblings', 'respect', 'love', 'support', 'tradition'] },
  { id: 26, category: 'social', title: 'Festivals & Culture', difficulty: 'Intermediate',
    subtopics: ['Celebrations', 'Traditions', 'Food & Music', 'Cultural Exchange'],
    keywords: ['Diwali', 'culture', 'rituals', 'joy', 'dance', 'heritage'] },
  { id: 27, category: 'social', title: 'Social Media', difficulty: 'Intermediate',
    subtopics: ['Usage & Impact', 'Pros & Cons', 'Digital Addiction', 'Content Creation'],
    keywords: ['Instagram', 'content', 'online', 'influence', 'privacy', 'followers'] },
  { id: 28, category: 'social', title: 'Community & Volunteering', difficulty: 'Intermediate',
    subtopics: ['Social Work', 'NGOs', 'Community Service', 'Making a Difference'],
    keywords: ['help', 'donate', 'volunteer', 'charity', 'impact', 'society'] },
  { id: 29, category: 'social', title: 'Gender & Equality', difficulty: 'Advanced',
    subtopics: ['Workplace Equality', 'Education Access', 'Social Norms', 'Empowerment'],
    keywords: ['equal', 'rights', 'opportunity', 'bias', 'respect', 'diversity'] },
  { id: 30, category: 'social', title: 'Manners & Etiquette', difficulty: 'Beginner',
    subtopics: ['Greetings', 'Table Manners', 'Formal Events', 'Cultural Differences'],
    keywords: ['polite', 'thank you', 'excuse me', 'respect', 'gesture', 'formal'] },

  // ─── Opinion & Debate ───
  { id: 31, category: 'opinion', title: 'Online vs Offline Education', difficulty: 'Intermediate',
    subtopics: ['Pros of Online', 'Benefits of Classroom', 'Hybrid Model', 'Student Perspective'],
    keywords: ['Zoom', 'classroom', 'flexibility', 'interaction', 'focus', 'access'] },
  { id: 32, category: 'opinion', title: 'Money & Happiness', difficulty: 'Intermediate',
    subtopics: ['Can Money Buy Happiness?', 'Wealth vs Health', 'Materialism', 'Simple Living'],
    keywords: ['money', 'contentment', 'luxury', 'struggle', 'priorities', 'satisfaction'] },
  { id: 33, category: 'opinion', title: 'Work-Life Balance', difficulty: 'Intermediate',
    subtopics: ['Burnout', 'Hobbies & Downtime', 'Remote Work', 'Setting Boundaries'],
    keywords: ['stress', 'relax', 'productivity', 'family time', 'vacation', 'boundaries'] },
  { id: 34, category: 'opinion', title: 'Social Media Influence', difficulty: 'Intermediate',
    subtopics: ['Fake News', 'Influencer Culture', 'Mental Health Impact', 'Cyberbullying'],
    keywords: ['viral', 'misinformation', 'trolling', 'followers', 'authentic', 'algorithm'] },
  { id: 35, category: 'opinion', title: 'Should AI Replace Jobs?', difficulty: 'Advanced',
    subtopics: ['Automation', 'Human Creativity', 'Economic Impact', 'Ethical Concerns'],
    keywords: ['robot', 'employment', 'efficiency', 'skill', 'displacement', 'regulate'] },
  { id: 36, category: 'opinion', title: 'Importance of Sports', difficulty: 'Beginner',
    subtopics: ['Physical Benefits', 'Team Spirit', 'Sports in Education', 'Famous Athletes'],
    keywords: ['fitness', 'discipline', 'competition', 'sportsmanship', 'Olympics', 'practice'] },
  { id: 37, category: 'opinion', title: 'City vs Village Life', difficulty: 'Beginner',
    subtopics: ['Lifestyle Differences', 'Job Opportunities', 'Nature & Peace', 'Community Bonds'],
    keywords: ['urban', 'rural', 'pollution', 'peaceful', 'opportunity', 'farming'] },

  // ─── Creative & Fun ───
  { id: 38, category: 'creative', title: 'Hobbies & Interests', difficulty: 'Beginner',
    subtopics: ['Indoor Hobbies', 'Outdoor Adventures', 'Creative Arts', 'Collecting Things'],
    keywords: ['reading', 'sports', 'music', 'passion', 'painting', 'gardening'] },
  { id: 39, category: 'creative', title: 'Movies & Entertainment', difficulty: 'Beginner',
    subtopics: ['Favorite Movie', 'Genres', 'Streaming Platforms', 'Movie Reviews'],
    keywords: ['cinema', 'actor', 'drama', 'comedy', 'thriller', 'Netflix'] },
  { id: 40, category: 'creative', title: 'Music & Dance', difficulty: 'Beginner',
    subtopics: ['Favorite Music', 'Instruments', 'Dance Styles', 'Live Concerts'],
    keywords: ['song', 'melody', 'guitar', 'rhythm', 'performance', 'lyrics'] },
  { id: 41, category: 'creative', title: 'Storytelling', difficulty: 'Intermediate',
    subtopics: ['Personal Stories', 'Fictional Tales', 'Moral Stories', 'Funny Incidents'],
    keywords: ['once upon a time', 'character', 'plot', 'twist', 'lesson', 'imagination'] },
  { id: 42, category: 'creative', title: 'Dream Vacation', difficulty: 'Beginner',
    subtopics: ['Dream Destination', 'Activities', 'Companions', 'Budget'],
    keywords: ['beach', 'mountains', 'abroad', 'adventure', 'luxury', 'backpacking'] },
  { id: 43, category: 'creative', title: 'If I Were...', difficulty: 'Intermediate',
    subtopics: ['Prime Minister', 'Billionaire', 'Invisible', 'Time Traveler'],
    keywords: ['imagine', 'change', 'power', 'wish', 'dream', 'possibility'] },
  { id: 44, category: 'creative', title: 'My Role Model', difficulty: 'Beginner',
    subtopics: ['Who & Why', 'Their Achievements', 'Qualities I Admire', 'Influence on Me'],
    keywords: ['inspire', 'hero', 'mentor', 'admire', 'follow', 'impact'] },
  { id: 45, category: 'creative', title: 'Describe a Picture', difficulty: 'Intermediate',
    subtopics: ['Scene Description', 'People & Actions', 'Emotions', 'Story Behind It'],
    keywords: ['observe', 'describe', 'vivid', 'detail', 'scene', 'express'] },
];
